// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// colonization
double colonization(double envir, double maxcolo, double opti, double width);
RcppExport SEXP biogeonet_colonization(SEXP envirSEXP, SEXP maxcoloSEXP, SEXP optiSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type envir(envirSEXP);
    Rcpp::traits::input_parameter< double >::type maxcolo(maxcoloSEXP);
    Rcpp::traits::input_parameter< double >::type opti(optiSEXP);
    Rcpp::traits::input_parameter< double >::type width(widthSEXP);
    rcpp_result_gen = Rcpp::wrap(colonization(envir, maxcolo, opti, width));
    return rcpp_result_gen;
END_RCPP
}
// extinction
double extinction(double inter, double basexti, double mn, double mx, double shape);
RcppExport SEXP biogeonet_extinction(SEXP interSEXP, SEXP basextiSEXP, SEXP mnSEXP, SEXP mxSEXP, SEXP shapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type inter(interSEXP);
    Rcpp::traits::input_parameter< double >::type basexti(basextiSEXP);
    Rcpp::traits::input_parameter< double >::type mn(mnSEXP);
    Rcpp::traits::input_parameter< double >::type mx(mxSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    rcpp_result_gen = Rcpp::wrap(extinction(inter, basexti, mn, mx, shape));
    return rcpp_result_gen;
END_RCPP
}
// nicheModel
NumericMatrix nicheModel(int nbsp, double connec, int mode);
RcppExport SEXP biogeonet_nicheModel(SEXP nbspSEXP, SEXP connecSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nbsp(nbspSEXP);
    Rcpp::traits::input_parameter< double >::type connec(connecSEXP);
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(nicheModel(nbsp, connec, mode));
    return rcpp_result_gen;
END_RCPP
}
