# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name extinction
#' @title Extinction rate for a given set of biotic interactions.
#' @description This function returns the extinction associated with a given biotic environment.
#'
#' @author
#' Kevin Cazelles
#'
#' @param inter a real number giving the sum of interactions.
#' @param basexti extinction rate without interaction.
#' @param mn a real number giving the minimum rate of extinction.
#' @param mx a real number giving the maximum rate of extinction.
#' @param shape a positive real number controlling the impact of biotic interactions: the larger the value the stronger the impact of interactions.
#'
#' @return Returns the extinction rate associated with a given biotic environment.
#'
#' @references
#' Cazelles, K., Mouquet, N., Mouillot, D. & Gravel, D. On the integration of
#' biotic interaction and environmental constraints at the biogeographical scale.
#' (equation 5).
#' @export
extinction <- function(inter, basexti, mn, mx, shape) {
    .Call('_biogeonet_extinction', PACKAGE = 'biogeonet', inter, basexti, mn, mx, shape)
}

#' @name colonization
#' @title Colonisation rate in a given abtiotic environment.
#' @description This function returns a colonisation rate in a given abtiotic environment.
#' This colonisation function is hump-shaped and its parameters allow for controlling
#' the height and the width of the hump.
#'
#' @param envir a real number giving the abiotic value.
#' @param maxcolo extinction rate associated with the optimum value, it controls the height of the hump.
#' @param opti a real number giving the optimum value, i.e the abiotic values at which the colonisation rate is maximal.
#' @param width a real number controlling the width of the hump, the larger the wider the hump.
#'
#' @return Returns the colonisation rate associated with a given biotic environment.
#'
#' @references
#' Cazelles, K., Mouquet, N., Mouillot, D. & Gravel, D. On the integration of
#' biotic interaction and environmental constraints at the biogeographical scale.
#' (equation 9).
#' @export
colonization <- function(envir, maxcolo, opti, width) {
    .Call('_biogeonet_colonization', PACKAGE = 'biogeonet', envir, maxcolo, opti, width)
}

#' @name buildMarkov
#' @title Generates the transition matrix for a given probability and  an interaction network using the niche model.
#' @description Generates the transition matrix for a given probability and  an interaction network using the niche model.
#'
#' @author
#' Kevin Cazelles
#'
#' @param nbsp an integer giving the number of species.
#' @param colo a vector giving the colonization rates of all species.
#' @param metaweb a matrix describing the interaction network.
#' @param basexti extinction rate without interaction.
#' @param mn a real number giving the minimum rate of extinction.
#' @param mx a real number giving the maximum rate of extinction.
#' @param shape a positive real number controlling the impact of biotic interactions: the larger the value the stronger the impact of interactions.
#'
#' @return Returns the transition matrix of the Markov chain to be solved.
#'
#' @references
#' Cazelles, K., Mouquet, N., Mouillot, D. & Gravel, D. On the integration of
#' biotic interaction and environmental constraints at the biogeographical scale.
#' @export
buildMarkov <- function(nbsp, colo, metaweb, basexti, mn, mx, shape) {
    .Call('_biogeonet_buildMarkov', PACKAGE = 'biogeonet', nbsp, colo, metaweb, basexti, mn, mx, shape)
}

#' @name getEigenElements
#' @title Markov transition matrix solver.
#' @description Solve the Markov transition matrix and return the eigen vector giving
#' the probability of presence associated with all the network's species.
#'
#' @author
#' Kevin Cazelles
#'
#' @param markov A transition matrix of a Markov chain.
#'
#' @return Returns the eigen values associated to the vector and eigen values
#' transition matrix of the Markov chain to be solved.
#'
#' @export
NULL

#' @name getEigenElementsSp
#' @title Markov transition matrix solver for sparse transition matriices.
#' @description Solve the Markov transition matrix and return the eigen vector giving
#' the probability of presence associated with all the network's species.
#'
#' @author
#' Kevin Cazelles
#'
#' @param smarkov A sparse transition matrix of a Markov chain.
#'
#' @return Returns the eigen values associated to the vector and eigen values
#' transition matrix of the markov chain to be solved.
#'
#' @export
NULL

getEigenElements <- function(markov) {
    .Call('_biogeonet_getEigenElements', PACKAGE = 'biogeonet', markov)
}

getEigenElementsSp <- function(smarkov) {
    .Call('_biogeonet_getEigenElementsSp', PACKAGE = 'biogeonet', smarkov)
}

#' @name nicheModel
#' @title Generate an interaction network using the niche model.
#' @description This function returns an interaction network using the model
#' proposed by Williams & Martinez (2000), the sign of coefficients can be
#' modified to simulate different kind of network.
#'
#' @author
#' Kevin Cazelles
#'
#' @param nbsp an integer, the number of species.
#' @param connec a real number giving the connectance of the network to be generated (between 0 and .5).
#' @param mode an integer used to select the sign used in the network (1- for predation; 2-competition;  3-nutualism)  a real number giving the optimum value, i.e the abiotic values at which the colonisation rate is maximal.
#'
#' @return Returns a numeric matrix describing the interaction network.
#'
#' @references
#' Williams, R. J. & Martinez, N. D. Simple rules yield complex food webs.
#' Nature 404, 180-183 (2000).
#'
#' @export
nicheModel <- function(nbsp, connec, mode) {
    .Call('_biogeonet_nicheModel', PACKAGE = 'biogeonet', nbsp, connec, mode)
}

